from utils import is_prime, prime_gen

# b must be prime and therefore positive
# a must be odd

def consecutive_primes(a, b):
    '''
    Find the number of consecutive primes generated by
    an a, b pair in the expression n^2 + a*n + b
    '''
    n = 0
    while is_prime(n*n + a*n + b):
        n += 1
    return n

most_primes = 0
coeffs = 0

# b must be prime because n^2 + an + b must be prime for n=0
for b in prime_gen(1000):
    for a in range(-999, 999, 2):
        cp = consecutive_primes(a, b)
        if cp > most_primes:
            most_primes = cp
            coeffs = a*b

print coeffs
