'''
Find the number of distinct values generated by a^b for 1 < a < 101 and 1 < b < 101.
'''
UPPER = 101
nums = []

for a in range(2, UPPER):
    for b in range(2, UPPER):
        nums.append(a**b)

s = set(nums)

print len(s) 
